### ISSUE TITLE
can't download cliwoc tsv file?

### ISSUE THREAD

**Issue by SimonCoulombe** [stvno/stvno.github.io#1]
Hi Steven, 
first, a big thank you for converting the data to non-access files :)

I'm trying to download the .TSV file at https://github.com/stvno/stvno.github.io/raw/master/page/cliwoc/CLIWOC21.tsv , but all I get are the following three lines :+1: 
 3 lines (3 sloc) 160 MB
--------------
version https://git-lfs.github.com/spec/v1
oid sha256:af04ddcf684e340a2f6f593ebf08cc37080273977b86fad92840e83396e5b893
size 167322650
------

The commit message says " added the files in LFS - I think". Guess there is something I dont understand with large file storage since these 3 lines dont take up 160MB..

**Comment by stvno** [comment]
Yeah git-lfs is not my friend. Probably way too late, but the files are not hosted at https://www.historicalclimatology.com/cliwoc.html

**Comment by SimonCoulombe** [comment]
Thanks ! I had compeltely forgot about this.  I think your link is where I ended up getting the data.   Here's the video I ended up doing with it https://www.youtube.com/watch?v=S2HCMUo_oc0&t=1s
